<!-- :::::::::::::: Scripts ::::::::::::::::: -->
	<!-- jquery -->
	<!--[if lt IE 9]>
	    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<![endif]-->
	<!--[if gte IE 9]><!-->
		<script src="/appcont/aa14aAppointments/jquery/jquery-2.1.4.min.js"></script>
	<!--<![endif]-->	
	<script src="/appcont/aa14aAppointments/jquery/jquery-ui.min.js"></script>
	<script src="/appcont/aa14aAppointments/jquery/jquery.ui.datepicker-${langCode}.js"></script>
	<script src="/appcont/aa14aAppointments/jquery-timepicker/jquery.timepicker.min.js"></script>
	
	<!-- Moment -->
	<script src="/appcont/aa14aAppointments/lib/moment-with-locales.min.js"></script>
	
	<!-- tinyMCE -->
	<script src='/appcont/aa14aAppointments/tinymce/tinymce.min.js'></script>

	<!-- aa14a -->
	<script src="/appcont/aa14aAppointments/scripts/aa14a-main.js"></script>
	<script src="/appcont/aa14aAppointments/scripts/aa14a-dates.js"></script>
	
	<script src="/appcont/aa14aAppointments/scripts/aa14a-appointmentEditDialog.js"></script>
	<script src="/appcont/aa14aAppointments/scripts/aa14a-bookedSlotRelease.js"></script>
