
<input type="hidden" id="numberOfAdjacentSlots" name="numberOfAdjacentSlots" />	
	
<form id="aa14a_editAppointment_form" action="" method="post" class='aa14a_form'>
	<input type="hidden" id="lang" name="lang" value='${langCode}'/>
	<input type="hidden" id="appointmentDateTime" name="appointmentDateTime" />
	<input type="hidden" id="slotOid" name="slotOid" />
	<input type="hidden" id="op" name="op" />

	
