CREATE TABLE AA14BUSINESSCONFIGT00 (OID VARCHAR(50) NOT NULL, LASTMODIFIED_AT DATETIME, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14ENTITYT00 (OID VARCHAR(50) NOT NULL, TYPE VARCHAR(3), BUSINESS_ID VARCHAR(50) NOT NULL, CREATED_AT DATETIME, CREATED_BY VARCHAR(50), DESCRIPTOR LONGTEXT, ENTITY_VERSION BIGINT, DEEPTH INTEGER, ID VARCHAR(150) NOT NULL, LASTMODIFIED_AT DATETIME, UPDATED_BY VARCHAR(50), NAME_EU VARCHAR(200) NOT NULL, NAME_ES VARCHAR(200) NOT NULL, DIVISION_ID VARCHAR(50), DIVISION_OID VARCHAR(50), SERVICE_ID VARCHAR(50), SERVICE_OID VARCHAR(50), ORGANIZATION_ID VARCHAR(50), ORGANIZATION_OID VARCHAR(50), PRIMARY KEY (OID)) engine=InnoDB
CREATE INDEX IX_AA14ENTITYT00_FK_AA14ENTITYT00_SERVICE_OID ON AA14ENTITYT00 (SERVICE_OID)
CREATE INDEX IX_AA14ENTITYT00_FK_AA14ENTITYT00_ORGANIZATION_OID ON AA14ENTITYT00 (ORGANIZATION_OID)
CREATE INDEX IX_AA14ENTITYT00_FK_AA14ENTITYT00_DIVISION_OID ON AA14ENTITYT00 (DIVISION_OID)
CREATE TABLE AA14ORGANIZATIONT00 (OID VARCHAR(50) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14DIVISIONT00 (OID VARCHAR(50) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14SERVICET00 (OID VARCHAR(50) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14LOCATIONT00 (OID VARCHAR(50) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14SCHEDULET00 (OID VARCHAR(50) NOT NULL, BUSINESS_ID VARCHAR(50) NOT NULL, CREATED_AT DATETIME, CREATED_BY VARCHAR(50), DESCRIPTOR LONGTEXT, ENTITY_VERSION BIGINT, ID VARCHAR(150) NOT NULL, LASTMODIFIED_AT DATETIME, UPDATED_BY VARCHAR(50), NAME_EU VARCHAR(200) NOT NULL, NAME_ES VARCHAR(200) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14BOOKEDSLOTT00 (OID VARCHAR(50) NOT NULL, TYPE VARCHAR(31), CREATED_AT DATETIME, CREATED_BY VARCHAR(50), DAY_OF_MONTH INTEGER NOT NULL, DESCRIPTOR LONGTEXT, DURATION_IN_MINUTES INTEGER NOT NULL, END_DATE DATETIME, ENTITY_VERSION BIGINT, HOUR_OF_DAY INTEGER NOT NULL, ID VARCHAR(200) NOT NULL, LASTMODIFIED_AT DATETIME, UPDATED_BY VARCHAR(50), MINUTES_OF_HOUR INTEGER NOT NULL, MONTH_OF_YEAR INTEGER NOT NULL, DIVISION_ID VARCHAR(50), DIVISION_OID VARCHAR(50), SERVICE_ID VARCHAR(50), LOCATION_ID VARCHAR(50), LOCATION_OID VARCHAR(50), SERVICE_OID VARCHAR(50), ORGANIZATION_ID VARCHAR(50), ORGANIZATION_OID VARCHAR(50), SCHEDULE_ID VARCHAR(50), SCHEDULE_OID VARCHAR(50), START_DATE DATETIME, YEAR INTEGER NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE INDEX AA14BOOKEDSLOTT00FK_AA14BOOKEDSLOTT00_LOCATION_OID ON AA14BOOKEDSLOTT00 (LOCATION_OID)
CREATE INDEX AA14BOOKEDSLOTT00FK_AA14BOOKEDSLOTT00_SCHEDULE_OID ON AA14BOOKEDSLOTT00 (SCHEDULE_OID)
CREATE TABLE AA14APPOINTMENTT00 (OID VARCHAR(50) NOT NULL, CONTACT_EMAIL VARCHAR(100), PERSON_ID VARCHAR(15) NOT NULL, PERSON_LOCATOR_ID VARCHAR(50), PERSON_SUMMARY VARCHAR(200) NOT NULL, SUBJECT_ID VARCHAR(200) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14NONBOOKABLET00 (OID VARCHAR(50) NOT NULL, PERIODIC_SERIE_OID VARCHAR(50), SUBJECT VARCHAR(200) NOT NULL, USER_ID VARCHAR(15) NOT NULL, PRIMARY KEY (OID)) engine=InnoDB
CREATE TABLE AA14SCHEDULE_LOCATIONT00 (LOCATION_OID VARCHAR(50) NOT NULL, SCHEDULE_OID VARCHAR(50) NOT NULL, PRIMARY KEY (LOCATION_OID, SCHEDULE_OID)) engine=InnoDB
CREATE INDEX 14SCHDLLOCATIONT00FK14SCHDLELOCATIONT00LOCATIONOID ON AA14SCHEDULE_LOCATIONT00 (LOCATION_OID)
CREATE INDEX 14SCHDLLOCATIONT00FK14SCHDLELOCATIONT00SCHEDULEOID ON AA14SCHEDULE_LOCATIONT00 (SCHEDULE_OID)
ALTER TABLE AA14ENTITYT00 ADD CONSTRAINT FK_AA14ENTITYT00_SERVICE_OID FOREIGN KEY (SERVICE_OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14ENTITYT00 ADD CONSTRAINT FK_AA14ENTITYT00_ORGANIZATION_OID FOREIGN KEY (ORGANIZATION_OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14ENTITYT00 ADD CONSTRAINT FK_AA14ENTITYT00_DIVISION_OID FOREIGN KEY (DIVISION_OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14ORGANIZATIONT00 ADD CONSTRAINT FK_AA14ORGANIZATIONT00_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14DIVISIONT00 ADD CONSTRAINT FK_AA14DIVISIONT00_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14SERVICET00 ADD CONSTRAINT FK_AA14SERVICET00_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14LOCATIONT00 ADD CONSTRAINT FK_AA14LOCATIONT00_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14BOOKEDSLOTT00 ADD CONSTRAINT FK_AA14BOOKEDSLOTT00_LOCATION_OID FOREIGN KEY (LOCATION_OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14BOOKEDSLOTT00 ADD CONSTRAINT FK_AA14BOOKEDSLOTT00_SCHEDULE_OID FOREIGN KEY (SCHEDULE_OID) REFERENCES AA14SCHEDULET00 (OID)
ALTER TABLE AA14APPOINTMENTT00 ADD CONSTRAINT FK_AA14APPOINTMENTT00_OID FOREIGN KEY (OID) REFERENCES AA14BOOKEDSLOTT00 (OID)
ALTER TABLE AA14NONBOOKABLET00 ADD CONSTRAINT FK_AA14NONBOOKABLET00_OID FOREIGN KEY (OID) REFERENCES AA14BOOKEDSLOTT00 (OID)
ALTER TABLE AA14SCHEDULE_LOCATIONT00 ADD CONSTRAINT FK_AA14SCHEDULE_LOCATIONT00_LOCATION_OID FOREIGN KEY (LOCATION_OID) REFERENCES AA14ENTITYT00 (OID)
ALTER TABLE AA14SCHEDULE_LOCATIONT00 ADD CONSTRAINT FK_AA14SCHEDULE_LOCATIONT00_SCHEDULE_OID FOREIGN KEY (SCHEDULE_OID) REFERENCES AA14SCHEDULET00 (OID)
