/* *********************************************************** */
/*                     LIMPIEZA TABLAS                         */
/* *********************************************************** */
DELETE FROM AA14APPOINTMENTT00;
DELETE FROM AA14NONBOOKABLET00;
DELETE FROM AA14BOOKEDSLOTT00;
DELETE FROM AA14LOCATIONT00;
DELETE FROM AA14SCHEDULE_LOCATIONT00;
DELETE FROM AA14SCHEDULET00;
DELETE FROM AA14DIVISIONT00;
DELETE FROM AA14ORGANIZATIONT00;
DELETE FROM AA14SERVICET00;
DELETE FROM AA14ENTITYT00;


/* *********************************************************** */
/*                     BORRADO TABLAS                          */
/* *********************************************************** */
DROP TABLE AA14APPOINTMENTT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14NONBOOKABLET00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14BOOKEDSLOTT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14LOCATIONT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14SCHEDULE_LOCATIONT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14SCHEDULET00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14DIVISIONT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14ORGANIZATIONT00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14SERVICET00 CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14ENTITYT00 CASCADE CONSTRAINTS PURGE;


/* *********************************************************** */
/*                     CREACION TABLAS                         */
/* *********************************************************** */
CREATE TABLE AA14APPOINTMENTT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL ,
	PERSON_ID            VARCHAR2(15 BYTE) NOT NULL ,
	PERSON_SUMMARY       VARCHAR2(200 BYTE) NOT NULL ,
	SUBJECT_ID           VARCHAR2(200 BYTE) NOT NULL ,
	PERSON_LOCATOR_ID    VARCHAR2(50 BYTE) NULL ,
	CONTACT_EMAIL        VARCHAR2(100 BYTE) NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14APPOINTMENTT00 ON AA14APPOINTMENTT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14APPOINTMENTT00 ADD CONSTRAINT PK_AA14APPOINTMENTT00 PRIMARY KEY (OID);


CREATE TABLE AA14BOOKEDSLOTT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL ,
	TYPE                 VARCHAR2(31 BYTE) NULL ,
	CREATED_AT           DATE NULL ,
	CREATED_BY           VARCHAR2(50 BYTE) NULL ,
	DAY_OF_MONTH         NUMBER(10) NOT NULL ,
	DESCRIPTOR           CLOB NOT NULL ,
	DURATION_IN_MINUTES  NUMBER(10) NOT NULL ,
	END_DATE             DATE NULL ,
	ENTITY_VERSION       NUMBER(20) NULL ,
	HOUR_OF_DAY          NUMBER(10) NOT NULL ,
	ID                   VARCHAR2(200 BYTE) NOT NULL ,
	LASTMODIFIED_AT      DATE NULL ,
	UPDATED_BY           VARCHAR2(50 BYTE) NULL ,
	MINUTES_OF_HOUR      NUMBER(10) NOT NULL ,
	MONTH_OF_YEAR        NUMBER(10) NOT NULL ,
	DIVISION_ID          VARCHAR2(50 BYTE) NULL ,
	DIVISION_OID         VARCHAR2(50 BYTE) NULL ,
	LOCATION_ID          VARCHAR2(50 BYTE) NULL ,
	LOCATION_OID         VARCHAR2(50 BYTE) NULL ,
	SERVICE_ID           VARCHAR2(50 BYTE) NULL ,
	SERVICE_OID          VARCHAR2(50 BYTE) NULL ,
	ORGANIZATION_ID      VARCHAR2(50 BYTE) NULL ,
	ORGANIZATION_OID     VARCHAR2(50 BYTE) NULL ,
	SCHEDULE_ID          VARCHAR2(50 BYTE) NULL ,
	SCHEDULE_OID         VARCHAR2(50 BYTE) NULL ,
	START_DATE           DATE NULL ,
	YEAR                 NUMBER(10) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14BOOKEDSLOTT00 ON AA14BOOKEDSLOTT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14BOOKEDSLOTT00 ADD CONSTRAINT PK_AA14BOOKEDSLOTT00 PRIMARY KEY (OID);


CREATE TABLE AA14DIVISIONT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14DIVISIONT00 ON AA14DIVISIONT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14DIVISIONT00 ADD CONSTRAINT PK_AA14DIVISIONT00 PRIMARY KEY (OID);


CREATE TABLE AA14ENTITYT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL ,
	TYPE                 VARCHAR2(3 BYTE) NULL ,
	CREATED_AT           DATE NULL ,
	CREATED_BY           VARCHAR2(50 BYTE) NULL ,
	DESCRIPTOR           CLOB NOT NULL ,
	ENTITY_VERSION       NUMBER(20) NULL ,
	DEEPTH               NUMBER(10) NULL ,
	ID                   VARCHAR2(150 BYTE) NOT NULL ,
	LASTMODIFIED_AT      DATE NULL ,
	UPDATED_BY           VARCHAR2(50 BYTE) NULL ,
	NAME_EU              VARCHAR2(200 BYTE) NOT NULL ,
	NAME_ES              VARCHAR2(200 BYTE) NOT NULL ,
	DIVISION_ID          VARCHAR2(50 BYTE) NULL ,
	DIVISION_OID         VARCHAR2(50 BYTE) NULL ,
	SERVICE_ID           VARCHAR2(50 BYTE) NULL ,
	SERVICE_OID          VARCHAR2(50 BYTE) NULL ,
	ORGANIZATION_ID      VARCHAR2(50 BYTE) NULL ,
	ORGANIZATION_OID     VARCHAR2(50 BYTE) NULL ,
	BUSINESS_ID          VARCHAR2(50 BYTE) NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14ENTITYT00 ON AA14ENTITYT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14ENTITYT00 ADD CONSTRAINT PK_AA14ENTITYT00 PRIMARY KEY (OID);


CREATE TABLE AA14LOCATIONT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14LOCATIONT00 ON AA14LOCATIONT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14LOCATIONT00 ADD CONSTRAINT PK_AA14LOCATIONT00 PRIMARY KEY (OID);


CREATE TABLE AA14NONBOOKABLET00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL ,
	SUBJECT              VARCHAR2(200 BYTE) NOT NULL ,
	USER_ID              VARCHAR2(15 BYTE) NOT NULL ,
	PERIODIC_SERIE_OID   VARCHAR2(50 BYTE) NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14NONBOOKABLET00 ON AA14NONBOOKABLET00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14NONBOOKABLET00 ADD CONSTRAINT PK_AA14NONBOOKABLET00 PRIMARY KEY (OID);


CREATE TABLE AA14ORGANIZATIONT00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14ORGANIZATIONT00 ON AA14ORGANIZATIONT00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14ORGANIZATIONT00 ADD CONSTRAINT PK_AA14ORGANIZATIONT00 PRIMARY KEY (OID);


CREATE TABLE AA14SCHEDULE_LOCATIONT00
(
	LOCATION_OID         VARCHAR2(50 BYTE) NOT NULL ,
	SCHEDULE_OID         VARCHAR2(50 BYTE) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14SCHEDULE_LOCATIONT00 ON AA14SCHEDULE_LOCATIONT00(LOCATION_OID ASC,SCHEDULE_OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14SCHEDULE_LOCATIONT00 ADD CONSTRAINT PK_AA14SCHEDULE_LOCATIONT00 PRIMARY KEY (LOCATION_OID,SCHEDULE_OID);


CREATE TABLE AA14SCHEDULET00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL ,
	CREATED_AT           DATE NULL ,
	CREATED_BY           VARCHAR2(50 BYTE) NULL ,
	DESCRIPTOR           CLOB NULL ,
	ENTITY_VERSION       NUMBER(20) NULL ,
	ID                   VARCHAR2(150 BYTE) NOT NULL ,
	LASTMODIFIED_AT      DATE NULL ,
	UPDATED_BY           VARCHAR2(50 BYTE) NULL ,
	NAME_EU              VARCHAR2(200) NOT NULL ,
	NAME_ES              VARCHAR2(200 BYTE) NOT NULL ,
	BUSINESS_ID          VARCHAR2(50 BYTE) NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14SCHEDULET00 ON AA14SCHEDULET00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14SCHEDULET00 ADD CONSTRAINT PK_AA14SCHEDULET00 PRIMARY KEY (OID);


CREATE TABLE AA14SERVICET00
(
	OID                  VARCHAR2(50 BYTE) NOT NULL 
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX PK_AA14SERVICET00 ON AA14SERVICET00(OID ASC) TABLESPACE AA14B02E00;
ALTER TABLE AA14SERVICET00 ADD CONSTRAINT PK_AA14SERVICET00 PRIMARY KEY (OID);


/* *********************************************************** */
/*                     CREACION INDEX                          */
/* *********************************************************** */
CREATE INDEX AA14APPOINTMENTI01 ON AA14APPOINTMENTT00 UPPER(PERSON_LOCATOR_ID) TABLESPACE AA14B02E00;
CREATE INDEX AA14APPOINTMENTI02 ON AA14APPOINTMENTT00 UPPER(PERSON_LOCATOR_ID, PERSON_ID) TABLESPACE AA14B02E00;
CREATE INDEX AA14APPOINTMENTI03 ON AA14APPOINTMENTT00 UPPER(PERSON_ID, CONTACT_EMAIL) TABLESPACE AA14B02E00;


/* *********************************************************** */
/*                     CREACION FOREIGN                        */
/* *********************************************************** */
ALTER TABLE AA14APPOINTMENTT00 ADD (CONSTRAINT FK_BOOKEDSLOT_APPOINTMENT_OID FOREIGN KEY (OID) REFERENCES AA14BOOKEDSLOTT00 (OID));
ALTER TABLE AA14BOOKEDSLOTT00 ADD (CONSTRAINT FK_LOCAT_BOOKEDSLOT_LOCAT_OID FOREIGN KEY (LOCATION_OID) REFERENCES AA14LOCATIONT00 (OID));
ALTER TABLE AA14BOOKEDSLOTT00 ADD (CONSTRAINT FK_SCHED_BOOKEDSLOT_SCHED_OID FOREIGN KEY (SCHEDULE_OID) REFERENCES AA14SCHEDULET00 (OID));
ALTER TABLE AA14BOOKEDSLOTT00 ADD (CONSTRAINT FK_SERVI_BOOKEDSLOT_SERVI_OID FOREIGN KEY (SERVICE_OID) REFERENCES AA14SERVICET00 (OID));
ALTER TABLE AA14BOOKEDSLOTT00 ADD (CONSTRAINT FK_ORGAN_BOOKEDSLOT_ORGAN_OID FOREIGN KEY (ORGANIZATION_OID) REFERENCES AA14ORGANIZATIONT00 (OID));
ALTER TABLE AA14BOOKEDSLOTT00 ADD (CONSTRAINT FK_DIVIS_BOOKEDSLOT_DIVIS_OID FOREIGN KEY (DIVISION_OID) REFERENCES AA14DIVISIONT00 (OID));
ALTER TABLE AA14DIVISIONT00 ADD (CONSTRAINT FK_ENTITY_DIVISION_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID));
ALTER TABLE AA14LOCATIONT00 ADD (CONSTRAINT FK_ENTITY_LOCATION_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID));
ALTER TABLE AA14NONBOOKABLET00 ADD (CONSTRAINT FK_BOOKEDSLOT_NONBOOKABLE_OID FOREIGN KEY (OID) REFERENCES AA14BOOKEDSLOTT00 (OID));
ALTER TABLE AA14ORGANIZATIONT00 ADD (CONSTRAINT FK_ENTITY_ORGANIZ_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID));
ALTER TABLE AA14SCHEDULE_LOCATIONT00 ADD (CONSTRAINT FK_LOCAT_SCHED_LOC_LOCAT_OID FOREIGN KEY (LOCATION_OID) REFERENCES AA14LOCATIONT00 (OID));
ALTER TABLE AA14SCHEDULE_LOCATIONT00 ADD (CONSTRAINT FK_SCHED_SCHED_LOC_SCHED_OID FOREIGN KEY (SCHEDULE_OID) REFERENCES AA14SCHEDULET00 (OID));
ALTER TABLE AA14SERVICET00 ADD (CONSTRAINT FK_ENTITY_SERVICE_OID FOREIGN KEY (OID) REFERENCES AA14ENTITYT00 (OID));


/* ****************************************************************************************************************************************************** */
/*                                                                   QUARTZ                                                                               */
/* ****************************************************************************************************************************************************** */

/* *********************************************************** */
/*                     LIMPIEZA TABLAS                         */
/* *********************************************************** */
DELETE FROM AA14QFIRED_TRIGGERS;
DELETE FROM AA14QSIMPLE_TRIGGERS;
DELETE FROM AA14QSIMPROP_TRIGGERS;
DELETE FROM AA14QCRON_TRIGGERS;
DELETE FROM AA14QBLOB_TRIGGERS;
DELETE FROM AA14QTRIGGERS;
DELETE FROM AA14QJOB_DETAILS;
DELETE FROM AA14QCALENDARS;
DELETE FROM AA14QPAUSED_TRIGGER_GRPS;
DELETE FROM AA14QLOCKS;
DELETE FROM AA14QSCHEDULER_STATE;


/* *********************************************************** */
/*                     BORRADO TABLAS                          */
/* *********************************************************** */
DROP TABLE AA14QCALENDARS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QFIRED_TRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QBLOB_TRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QCRON_TRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QSIMPLE_TRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QSIMPROP_TRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QTRIGGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QJOB_DETAILS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QPAUSED_TRIGGER_GRPS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QLOCKS CASCADE CONSTRAINTS PURGE;
DROP TABLE AA14QSCHEDULER_STATE CASCADE CONSTRAINTS PURGE;


/* *********************************************************** */
/*                     CREACION TABLAS                         */
/* *********************************************************** */
CREATE TABLE AA14QJOB_DETAILS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	JOB_NAME             VARCHAR2(200) NOT NULL,
	JOB_GROUP            VARCHAR2(200) NOT NULL,
	DESCRIPTION          VARCHAR2(250) NULL,
	JOB_CLASS_NAME       VARCHAR2(250) NOT NULL, 
	IS_DURABLE           VARCHAR2(1) NOT NULL,
	IS_NONCONCURRENT     VARCHAR2(1) NOT NULL,
	IS_UPDATE_DATA       VARCHAR2(1) NOT NULL,
	REQUESTS_RECOVERY    VARCHAR2(1) NOT NULL,
	JOB_DATA             BLOB NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QJOB_DETAILS_PK ON AA14QJOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QJOB_DETAILS ADD CONSTRAINT AA14QJOB_DETAILS_PK PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP);


CREATE TABLE AA14QTRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	JOB_NAME             VARCHAR2(200) NOT NULL, 
	JOB_GROUP            VARCHAR2(200) NOT NULL,
	DESCRIPTION          VARCHAR2(250) NULL,
	NEXT_FIRE_TIME       NUMBER(13) NULL,
	PREV_FIRE_TIME       NUMBER(13) NULL,
	PRIORITY             NUMBER(13) NULL,
	TRIGGER_STATE        VARCHAR2(16) NOT NULL,
	TRIGGER_TYPE         VARCHAR2(8) NOT NULL,
	START_TIME           NUMBER(13) NOT NULL,
	END_TIME             NUMBER(13) NULL,
	CALENDAR_NAME        VARCHAR2(200) NULL,
	MISFIRE_INSTR        NUMBER(2) NULL,
	JOB_DATA             BLOB NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QTRIGGERS_PK ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QTRIGGERS ADD CONSTRAINT AA14QTRIGGERS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QSIMPLE_TRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	REPEAT_COUNT         NUMBER(7) NOT NULL,
	REPEAT_INTERVAL      NUMBER(12) NOT NULL,
	TIMES_TRIGGERED      NUMBER(10) NOT NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QSIMPLE_TRIG_PK ON AA14QSIMPLE_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QSIMPLE_TRIGGERS ADD CONSTRAINT AA14QSIMPLE_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QCRON_TRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	CRON_EXPRESSION      VARCHAR2(120) NOT NULL,
	TIME_ZONE_ID         VARCHAR2(80)
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QCRON_TRIG_PK ON AA14QCRON_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QCRON_TRIGGERS ADD CONSTRAINT AA14QCRON_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QSIMPROP_TRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	STR_PROP_1           VARCHAR2(512) NULL,
	STR_PROP_2           VARCHAR2(512) NULL,
	STR_PROP_3           VARCHAR2(512) NULL,
	INT_PROP_1           NUMBER(10) NULL,
	INT_PROP_2           NUMBER(10) NULL,
	LONG_PROP_1          NUMBER(13) NULL,
	LONG_PROP_2          NUMBER(13) NULL,
	DEC_PROP_1           NUMERIC(13,4) NULL,
	DEC_PROP_2           NUMERIC(13,4) NULL,
	BOOL_PROP_1          VARCHAR2(1) NULL,
	BOOL_PROP_2          VARCHAR2(1) NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QSIMPROP_TRIG_PK ON AA14QSIMPROP_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QSIMPROP_TRIGGERS ADD CONSTRAINT AA14QSIMPROP_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QBLOB_TRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	BLOB_DATA            BLOB NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QBLOB_TRIG_PK ON AA14QBLOB_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QBLOB_TRIGGERS ADD CONSTRAINT AA14QBLOB_TRIG_PK PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QCALENDARS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	CALENDAR_NAME        VARCHAR2(200) NOT NULL, 
	CALENDAR             BLOB NOT NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QCALENDARS_PK ON AA14QCALENDARS(SCHED_NAME,CALENDAR_NAME) TABLESPACE AA14B02E00;
ALTER TABLE AA14QCALENDARS ADD CONSTRAINT AA14QCALENDARS_PK PRIMARY KEY (SCHED_NAME,CALENDAR_NAME);


CREATE TABLE AA14QPAUSED_TRIGGER_GRPS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QPAUSED_TRIG_GRPS_PK ON AA14QPAUSED_TRIGGER_GRPS(SCHED_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
ALTER TABLE AA14QPAUSED_TRIGGER_GRPS ADD CONSTRAINT AA14QPAUSED_TRIG_GRPS_PK PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP);


CREATE TABLE AA14QFIRED_TRIGGERS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	ENTRY_ID             VARCHAR2(95) NOT NULL,
	TRIGGER_NAME         VARCHAR2(200) NOT NULL,
	TRIGGER_GROUP        VARCHAR2(200) NOT NULL,
	INSTANCE_NAME        VARCHAR2(200) NOT NULL,
	FIRED_TIME           NUMBER(13) NOT NULL,
	SCHED_TIME           NUMBER(13) NOT NULL,
	PRIORITY             NUMBER(13) NOT NULL,
	STATE                VARCHAR2(16) NOT NULL,
	JOB_NAME             VARCHAR2(200) NULL,
	JOB_GROUP            VARCHAR2(200) NULL,
	IS_NONCONCURRENT     VARCHAR2(1) NULL,
	REQUESTS_RECOVERY    VARCHAR2(1) NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QFIRED_TRIGGER_PK ON AA14QFIRED_TRIGGERS(SCHED_NAME,ENTRY_ID) TABLESPACE AA14B02E00;
ALTER TABLE AA14QFIRED_TRIGGERS ADD CONSTRAINT AA14QFIRED_TRIGGER_PK PRIMARY KEY (SCHED_NAME,ENTRY_ID);


CREATE TABLE AA14QSCHEDULER_STATE 
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	INSTANCE_NAME        VARCHAR2(200) NOT NULL,
	LAST_CHECKIN_TIME    NUMBER(13) NOT NULL,
	CHECKIN_INTERVAL     NUMBER(13) NOT NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QSCHEDULER_STATE_PK ON AA14QSCHEDULER_STATE(SCHED_NAME,INSTANCE_NAME) TABLESPACE AA14B02E00;
ALTER TABLE AA14QSCHEDULER_STATE ADD CONSTRAINT AA14QSCHEDULER_STATE_PK PRIMARY KEY (SCHED_NAME,INSTANCE_NAME);


CREATE TABLE AA14QLOCKS
(
	SCHED_NAME           VARCHAR2(120) NOT NULL,
	LOCK_NAME            VARCHAR2(40) NOT NULL
)
TABLESPACE AA14B01E00;

CREATE UNIQUE INDEX AA14QLOCKS_PK ON AA14QLOCKS(SCHED_NAME,LOCK_NAME) TABLESPACE AA14B02E00;
ALTER TABLE AA14QLOCKS ADD CONSTRAINT AA14QLOCKS_PK PRIMARY KEY (SCHED_NAME,LOCK_NAME);


/* *********************************************************** */
/*                     CREACION INDEX                          */
/* *********************************************************** */
CREATE INDEX IDX_AA14QJ_REQ_RECOVERY ON AA14QJOB_DETAILS(SCHED_NAME,REQUESTS_RECOVERY) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QJ_GRP ON AA14QJOB_DETAILS(SCHED_NAME,JOB_GROUP) TABLESPACE AA14B02E00;

CREATE INDEX IDX_AA14QT_J ON AA14QTRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_JG ON AA14QTRIGGERS(SCHED_NAME,JOB_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_C ON AA14QTRIGGERS(SCHED_NAME,CALENDAR_NAME) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_G ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_STATE ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_STATE) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_N_STATE ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_N_G_STATE ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_NEXT_FIRE_TIME ON AA14QTRIGGERS(SCHED_NAME,NEXT_FIRE_TIME) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_NFT_ST ON AA14QTRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_NFT_MISFIRE ON AA14QTRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_NFT_ST_MISFIRE ON AA14QTRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QT_NFT_ST_MISFIRE_GRP ON AA14QTRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE) TABLESPACE AA14B02E00;

CREATE INDEX IDX_AA14QFT_TRIG_INST_NAME ON AA14QFIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QFT_INST_JOB_REQ_RCVRY ON AA14QFIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QFT_J_G ON AA14QFIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QFT_JG ON AA14QFIRED_TRIGGERS(SCHED_NAME,JOB_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QFT_T_G ON AA14QFIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;
CREATE INDEX IDX_AA14QFT_TG ON AA14QFIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP) TABLESPACE AA14B02E00;


/* *********************************************************** */
/*                     CREACION FOREIGN                        */
/* *********************************************************** */
ALTER TABLE AA14QTRIGGERS ADD (CONSTRAINT AA14QTRIGGER_TO_JOBS_FK FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES AA14QJOB_DETAILS (SCHED_NAME,JOB_NAME,JOB_GROUP));
ALTER TABLE AA14QSIMPLE_TRIGGERS ADD (CONSTRAINT AA14QSIMPLE_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES AA14QTRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));
ALTER TABLE AA14QCRON_TRIGGERS ADD (CONSTRAINT AA14QCRON_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES AA14QTRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));
ALTER TABLE AA14QSIMPROP_TRIGGERS ADD (CONSTRAINT AA14QSIMPROP_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES AA14QTRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));
ALTER TABLE AA14QBLOB_TRIGGERS ADD (CONSTRAINT AA14QBLOB_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) REFERENCES AA14QTRIGGERS (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP));


